#ifndef FRAME_H
#define FRAME_H
#include <stdint.h>

#define SOF_SIZE             2u
#define TX_FRAME_HEADER_SIZE 10u
#define TX_FRAME_CAPACITY    1344u

#define WHEEL_ROTATION_Q6_SCALE    64u
#define ENCODER_FRAME_PAYLOAD_SIZE 4u
#define MOTOR_COMMAND_PAYLOAD_SIZE ENCODER_FRAME_PAYLOAD_SIZE

extern const uint8_t START_OF_FRAME[SOF_SIZE];

typedef enum
{
        FRAME_TYPE_LIDAR               = 0x01,
        FRAME_TYPE_IMU                 = 0x02,
        FRAME_TYPE_ENC                 = 0x03,
        FRAME_TYPE_INITIALIZING        = 0x04,
        FRAME_TYPE_DEVICE_INFO         = 0x05,
        FRAME_TYPE_HEALTH_STATUS       = 0x06,
        FRAME_TYPE_READY               = 0x07,
        FRAME_TYPE_STARTUP_FAILED      = 0x08,
        FRAME_TYPE_START_SCAN_ACK      = 0x09,
        FRAME_TYPE_TIME_SYNC_START_ACK = 0x0A,
        FRAME_TYPE_TIME_ACK            = 0x0B,
        FRAME_TYPE_TIME_SYNC_REPORT    = 0x0C,
        FRAME_TYPE_HANDSHAKE_ACK       = 0x0D,
        FRAME_TYPE_MOTOR_ACK           = 0x0E,
        FRAME_TYPE_SOFT_RESET_ACK      = 0x0F,
} FrameType;

typedef enum
{
        // HOST_COMMAND_GET_STATUS,
        HOST_COMMAND_START_SCAN,
        // HOST_COMMAND_END_SCAN,
        HOST_COMMAND_TIME_SYNC_START,
        HOST_COMMAND_TIME,
        HOST_COMMAND_HANDSHAKE,
        HOST_COMMAND_SOFT_RESET,
        HOST_COMMAND_MOTOR,
        HOST_COMMAND_COUNT,
} HostCommand;

#define HOST_COMMAND_SIZE 2u

#define HOST_MOTOR_COMMAND_SIZE (HOST_COMMAND_SIZE + MOTOR_COMMAND_PAYLOAD_SIZE)

#define HOST_HANDSHAKE_RETRY_INTERVAL_MS 3000u

extern const uint8_t HOST_COMMANDS[HOST_COMMAND_COUNT][HOST_COMMAND_SIZE];

#define FRAME_MESSAGE_INITIALIZING        "INITIALIZING"
#define FRAME_MESSAGE_READY               "READY"
#define FRAME_MESSAGE_STARTUP_FAILED      "STARTUP FAILED"
#define FRAME_MESSAGE_START_SCAN_ACK      "START SCAN ACK"
#define FRAME_MESSAGE_TIME_SYNC_START_ACK "TIME SYNC START ACK"
#define FRAME_MESSAGE_TIME_ACK            "TIME ACK"
#define FRAME_MESSAGE_HANDSHAKE_ACK       "HANDSHAKE ACK"
#define FRAME_MESSAGE_MOTOR_ACK           "MOTOR ACK"
#define FRAME_MESSAGE_SOFT_RESET_ACK      "SOFT RESET ACK"

#endif
